$baseUrl = "http://localhost:5165"
$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession

# 1. Login
$loginUrl = "$baseUrl/Account/Login"
$loginBody = @{
    "Input.Email" = "anchorcorp@anchor.com"
    "Input.Password" = "AnchorPro!123"
}
try {
    Invoke-WebRequest -Uri $loginUrl -Method Post -Body $loginBody -WebSession $session -ErrorAction Stop | Out-Null
} catch {
    # Expected to redirect on success
}

function Invoke-Api {
    param($Uri, $Method, $Body, $ContentType = "application/json")
    try {
        if ($Body) {
            return Invoke-RestMethod -Uri $Uri -Method $Method -Body $Body -ContentType $ContentType -WebSession $session
        } else {
            return Invoke-RestMethod -Uri $Uri -Method $Method -WebSession $session
        }
    } catch {
        $errorResponse = $_.Exception.Response
        if ($errorResponse) {
            $reader = New-Object System.IO.StreamReader($errorResponse.GetResponseStream())
            $body = $reader.ReadToEnd()
            Write-Host "ERROR: $Method $Uri returned $($errorResponse.StatusCode)"
            Write-Host "Response Body: $body"
        } else {
            Write-Host "ERROR: $_"
        }
        return $null
    }
}

Write-Host "`n--- 1. Testing Alerts API ---"

$unreadCountStart = Invoke-Api -Uri "$baseUrl/api/alerts/unread-count" -Method Get
Write-Host "Initial Unread Alerts Count: $unreadCountStart"

$newAlert = @{
    title = "Test Script Alert"
    message = "This is an alert generated by the test script"
    severity = "Info"
    category = "General"
} | ConvertTo-Json

Write-Host "Creating new alert..."
$createdAlert = Invoke-Api -Uri "$baseUrl/api/alerts" -Method Post -Body $newAlert
Write-Host "Created Alert ID: $($createdAlert.id)"

$unreadCountMiddle = Invoke-Api -Uri "$baseUrl/api/alerts/unread-count" -Method Get
Write-Host "Unread count after create: $unreadCountMiddle"

Write-Host "Marking alert as read..."
Invoke-Api -Uri "$baseUrl/api/alerts/$($createdAlert.id)/read" -Method Patch | Out-Null

$unreadCountEnd = Invoke-Api -Uri "$baseUrl/api/alerts/unread-count" -Method Get
Write-Host "Unread count after mark as read: $unreadCountEnd"

Write-Host "`n--- 2. Testing Job Card Read Endpoints ---"
$jobId = 1 # Assuming job 1 exists
Write-Host "Getting attachments for Job $jobId..."
$attachments = Invoke-Api -Uri "$baseUrl/api/jobcards/$jobId/attachments" -Method Get
Write-Host "Found $($attachments.Count) attachments."

Write-Host "Getting parts for Job $jobId..."
$parts = Invoke-Api -Uri "$baseUrl/api/jobcards/$jobId/parts" -Method Get
Write-Host "Found $($parts.Count) parts."

Write-Host "`n--- 3. Testing JobCards Status Filter ---"
$inProgressJobs = Invoke-Api -Uri "$baseUrl/api/jobcards?status=2" -Method Get
Write-Host "Found $($inProgressJobs.Count) jobs in InProgress status."

Write-Host "`nAll API tests completed successfully!"
